password = "sovet123"

# ВАЖНО ПРИ ИСПОЛЬЗОВАНИИ TOML-файлов!
# Наборы ASCII-символов можно применять без использовани кавычек
# В примере выше слово password состоит только из ASCII-символов
# Unicode наборы (слова) использовать только с кавычками! 

["Фамилия"]
"Котляров" = "Михаил"

# Подключение БД SQLite по локальному пути
# ВАЖНО! Использовать только ASCII-символы
[connections.la_sql]
url = "sqlite:///files/sqlite/LA.sqlite"