password = "sovet123"

# ВАЖНО ПРИ ИСПОЛЬЗОВАНИИ TOML-файлов!
# Наборы ASCII-символов можно применять без использовани кавычек
# В примере выше слово passwoкв состоит только из ASCII-символов
# Unicode наборы (слова) использовать только с кавычками! 

["Фамилия"]
"Котляров" = "Михаил"